/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MI_MAK;

import MI_MAK.dao.User;
import com.stripbandunk.jglasspane.helper.GraphicHelper;
import com.stripbandunk.jglasspane.transition.image.FadeImageTransition;
import java.awt.CardLayout;
import java.awt.Font;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Imam-pc
 */
public class MenuUtama extends javax.swing.JFrame {

   private User user;
    public MenuUtama() {
        
        this.setIconImage(new ImageIcon(getClass().getResource("/MI_MAK/image/logo_trans_48.png")).getImage());
         setExtendedState(MAXIMIZED_BOTH);
        jam();
        initComponents();
        
        Date now = new Date();
        Locale locale = new Locale("id","ID");
        SimpleDateFormat frm = new SimpleDateFormat("EEEE, dd MMMM YYYY",locale);
        SimpleDateFormat tm = new SimpleDateFormat("HH:mm:ss",locale);
        String tgl = frm.format(now);
        String times = tm.format(now);
        labelTgl.setText(tgl);
        lblJam.setText(times);
        
    }
    
    public User getUser(User param){
        
        labelName.setText(param.getFullname());
        //labelKategori.setText(param.getCategory());
        
        return user;
        
    }
    
    public void login(){
        Login login = new Login();
        
        login.setLocationRelativeTo(this);
        login.setVisible(true);
        
    }
    
    private void logout(){
        login();
    }
    
    private void jam(){
        ActionListener taskPerformer = new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
        String nol_bulan = "";
        String nol_hari = "";
        String nol_jam = "";
        String nol_menit = "";
        String nol_detik = "";
        // Membuat Date
        Date dt = new Date();
        // Mengambil nilaj JAM, MENIT, dan DETIK Sekarang
        int nilai_tahun = dt.getYear() + 1900;
        int nilai_bulan = dt.getMonth() + 1;
        int nilai_hari = dt.getDate();
        int nilai_jam = dt.getHours();
        int nilai_menit = dt.getMinutes();
        int nilai_detik = dt.getSeconds();
        // Jika nilai JAM lebih kecil dari 10 (hanya 1 digit)
        if (nilai_bulan <= 9) {
          // Tambahkan "0" didepannya
          nol_bulan = "0";
        }
        if (nilai_hari <= 9) {
          // Tambahkan "0" didepannya
          nol_hari = "0";
        }
        if (nilai_jam <= 9) {
          // Tambahkan "0" didepannya
          nol_jam = "0";
        }
        // Jika nilai MENIT lebih kecil dari 10 (hanya 1 digit)
        if (nilai_menit <= 9) {
          // Tambahkan "0" didepannya
          nol_menit = "0";
        }
        // Jika nilai DETIK lebih kecil dari 10 (hanya 1 digit)
        if (nilai_detik <= 9) {
          // Tambahkan "0" didepannya
          nol_detik = "0";
        }
        // Membuat String JAM, MENIT, DETIK
        String bulan = nol_bulan + Integer.toString(nilai_bulan);
        String hari = nol_hari + Integer.toString(nilai_hari);
        String jam = nol_jam + Integer.toString(nilai_jam);
        String menit = nol_menit + Integer.toString(nilai_menit);
        String detik = nol_detik + Integer.toString(nilai_detik);
        // Menampilkan pada Layar
       lblJam.setFont(new java.awt.Font("Digifacewide", Font.BOLD, 12));
      lblJam.setText(jam + " : " + menit + " : " + detik);
      } 
    };
    // Timer
    new Timer(1000, taskPerformer).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jGlassPane1 = new com.stripbandunk.jglasspane.JGlassPane();
        imageTransitionComponent1 = new com.stripbandunk.jglasspane.component.ImageTransitionComponent();
        panelImageBackground1 = new MI_MAK.widget.PanelImageBackground();
        panelMenu = new javax.swing.JPanel();
        btnExit = new usu.widget.glass.ButtonImageReflection();
        menuSiswa = new usu.widget.glass.ButtonImageReflection();
        menuGuru = new usu.widget.glass.ButtonImageReflection();
        menuMapel = new usu.widget.glass.ButtonImageReflection();
        menuNilai = new usu.widget.glass.ButtonImageReflection();
        menuAbsen = new usu.widget.glass.ButtonImageReflection();
        menuKelas = new usu.widget.glass.ButtonImageReflection();
        menuLaporan = new usu.widget.glass.ButtonImageReflection();
        menuUser = new usu.widget.glass.ButtonImageReflection();
        labelTgl = new javax.swing.JLabel();
        lblJam = new javax.swing.JLabel();
        labelLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        PanelCard = new javax.swing.JPanel();
        welcome1 = new MI_MAK.Welcome();
        panelSiswa1 = new MI_MAK.siswa.PanelSiswa();
        panelGuruTab1 = new MI_MAK.guru.PanelGuruTab();
        panelMapel1 = new MI_MAK.mapel.PanelMapel();
        panelNilaiTab1 = new MI_MAK.nilai.PanelNilaiTab();
        panelAbsen1 = new MI_MAK.absen.PanelAbsen();
        panelKelas1 = new MI_MAK.kelas.PanelKelas();
        panelLaporan1 = new MI_MAK.laporanPanel.PanelLaporan();
        panelUser1 = new MI_MAK.user.PanelUser();

        javax.swing.GroupLayout imageTransitionComponent1Layout = new javax.swing.GroupLayout(imageTransitionComponent1);
        imageTransitionComponent1.setLayout(imageTransitionComponent1Layout);
        imageTransitionComponent1Layout.setHorizontalGroup(
            imageTransitionComponent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        imageTransitionComponent1Layout.setVerticalGroup(
            imageTransitionComponent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        panelMenu.setBackground(new java.awt.Color(166, 229, 104));

        btnExit.setForeground(new java.awt.Color(0, 0, 0));
        btnExit.setText("Keluar");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        menuSiswa.setForeground(new java.awt.Color(0, 0, 0));
        menuSiswa.setText("Siswa");
        menuSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSiswaActionPerformed(evt);
            }
        });

        menuGuru.setForeground(new java.awt.Color(0, 0, 0));
        menuGuru.setText("Guru");
        menuGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGuruActionPerformed(evt);
            }
        });

        menuMapel.setForeground(new java.awt.Color(0, 0, 0));
        menuMapel.setText("Mata Pelajaran");
        menuMapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMapelActionPerformed(evt);
            }
        });

        menuNilai.setForeground(new java.awt.Color(0, 0, 0));
        menuNilai.setText("Nilai");
        menuNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNilaiActionPerformed(evt);
            }
        });

        menuAbsen.setForeground(new java.awt.Color(0, 0, 0));
        menuAbsen.setText("Absensi");
        menuAbsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbsenActionPerformed(evt);
            }
        });

        menuKelas.setForeground(new java.awt.Color(0, 0, 0));
        menuKelas.setText("Kelas");
        menuKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKelasActionPerformed(evt);
            }
        });

        menuLaporan.setForeground(new java.awt.Color(0, 0, 0));
        menuLaporan.setText("Laporan");
        menuLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLaporanActionPerformed(evt);
            }
        });

        menuUser.setForeground(new java.awt.Color(0, 0, 0));
        menuUser.setText("User");
        menuUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addComponent(menuSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menuGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menuMapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menuNilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menuAbsen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menuKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menuLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menuUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(menuSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(menuGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(menuMapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(menuNilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(menuAbsen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(menuKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(menuLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(menuUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        labelTgl.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        labelTgl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTgl.setText("jLabel1");

        lblJam.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        lblJam.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblJam.setText("jLabel1");

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MI_MAK/image/logo_baner.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setText("Perancangan Sistem Informasi Pengolahan Nilai Raport  ");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setText("DI MI MATHLA'UL ANWAR KOPO");

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel1.setText("Copyright © 2020 MI MATHLAUL ANWAR KOPO");

        labelName.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        labelName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelName.setText("FullName");

        PanelCard.setOpaque(false);
        PanelCard.setLayout(new java.awt.CardLayout());
        PanelCard.add(welcome1, "welcome");
        PanelCard.add(panelSiswa1, "siswa");
        PanelCard.add(panelGuruTab1, "guru");
        PanelCard.add(panelMapel1, "mapel");
        PanelCard.add(panelNilaiTab1, "nilai");
        PanelCard.add(panelAbsen1, "absen");
        PanelCard.add(panelKelas1, "kelas");
        PanelCard.add(panelLaporan1, "laporan");
        PanelCard.add(panelUser1, "user");

        javax.swing.GroupLayout panelImageBackground1Layout = new javax.swing.GroupLayout(panelImageBackground1);
        panelImageBackground1.setLayout(panelImageBackground1Layout);
        panelImageBackground1Layout.setHorizontalGroup(
            panelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImageBackground1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelImageBackground1Layout.createSequentialGroup()
                .addComponent(labelLogo)
                .addGap(18, 18, 18)
                .addGroup(panelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImageBackground1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelImageBackground1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblJam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTgl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelCard, javax.swing.GroupLayout.PREFERRED_SIZE, 1031, Short.MAX_VALUE)
        );
        panelImageBackground1Layout.setVerticalGroup(
            panelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImageBackground1Layout.createSequentialGroup()
                .addGroup(panelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelImageBackground1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)
                        .addGroup(panelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelImageBackground1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImageBackground1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelTgl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblJam)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelCard, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelName)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImageBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImageBackground1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:

        int closing;
        closing = JOptionPane.showConfirmDialog(this,
            "Apakah anda yakin, ingin keluar dari Aplikasi ini...?", "Konfirmasi",JOptionPane.YES_NO_OPTION);
        if (closing==0){
            System.exit(0);

        }else{
            this.show();
        }

    }//GEN-LAST:event_btnExitActionPerformed

    private void menuSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSiswaActionPerformed
        // TODO add your handling code here:
        FadeImageTransition transition = new FadeImageTransition();
        transition.setCoordinate(GraphicHelper.getLocation(PanelCard, jGlassPane1));

        imageTransitionComponent1.setTransition(transition);
        CardLayout layout = (CardLayout) PanelCard.getLayout();
        layout.show(PanelCard, "siswa");
        panelSiswa1.LoadSiswa();
    }//GEN-LAST:event_menuSiswaActionPerformed

    private void menuGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGuruActionPerformed
        // TODO add your handling code here:
        FadeImageTransition transition = new FadeImageTransition();
        transition.setCoordinate(GraphicHelper.getLocation(PanelCard, jGlassPane1));

        imageTransitionComponent1.setTransition(transition);
        CardLayout layout = (CardLayout) PanelCard.getLayout();
        layout.show(PanelCard, "guru");
        panelGuruTab1.LoadGuru();
    }//GEN-LAST:event_menuGuruActionPerformed

    private void menuMapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMapelActionPerformed
        // TODO add your handling code here:
        FadeImageTransition transition = new FadeImageTransition();
        transition.setCoordinate(GraphicHelper.getLocation(PanelCard, jGlassPane1));

        imageTransitionComponent1.setTransition(transition);
        CardLayout layout = (CardLayout) PanelCard.getLayout();
        layout.show(PanelCard, "mapel");
        panelMapel1.LoadMapel();
    }//GEN-LAST:event_menuMapelActionPerformed

    private void menuNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNilaiActionPerformed
        // TODO add your handling code here:
        FadeImageTransition transition = new FadeImageTransition();
        transition.setCoordinate(GraphicHelper.getLocation(PanelCard, jGlassPane1));

        imageTransitionComponent1.setTransition(transition);
        CardLayout layout = (CardLayout) PanelCard.getLayout();
        layout.show(PanelCard, "nilai");
        panelNilaiTab1.LoadComb();
    }//GEN-LAST:event_menuNilaiActionPerformed

    private void menuAbsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbsenActionPerformed
        // TODO add your handling code here:
        FadeImageTransition transition = new FadeImageTransition();
        transition.setCoordinate(GraphicHelper.getLocation(PanelCard, jGlassPane1));

        imageTransitionComponent1.setTransition(transition);
        CardLayout layout = (CardLayout) PanelCard.getLayout();
        layout.show(PanelCard, "absen");
        panelAbsen1.LoadAbsensi();
    }//GEN-LAST:event_menuAbsenActionPerformed

    private void menuKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKelasActionPerformed
        // TODO add your handling code here:
        FadeImageTransition transition = new FadeImageTransition();
        transition.setCoordinate(GraphicHelper.getLocation(PanelCard, jGlassPane1));

        imageTransitionComponent1.setTransition(transition);
        CardLayout layout = (CardLayout) PanelCard.getLayout();
        layout.show(PanelCard, "kelas");
        panelKelas1.LoadKelas();
    }//GEN-LAST:event_menuKelasActionPerformed

    private void menuLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLaporanActionPerformed
        // TODO add your handling code here:
        FadeImageTransition transition = new FadeImageTransition();
        transition.setCoordinate(GraphicHelper.getLocation(PanelCard, jGlassPane1));

        imageTransitionComponent1.setTransition(transition);
        CardLayout layout = (CardLayout) PanelCard.getLayout();
        layout.show(PanelCard, "laporan");
        panelLaporan1.LoadGuruCombo();
        panelLaporan1.LoadKelasCombo();
        panelLaporan1.LoadMapelCombo();
    }//GEN-LAST:event_menuLaporanActionPerformed

    private void menuUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUserActionPerformed
        // TODO add your handling code here:
        FadeImageTransition transition = new FadeImageTransition();
        transition.setCoordinate(GraphicHelper.getLocation(PanelCard, jGlassPane1));

        imageTransitionComponent1.setTransition(transition);
        CardLayout layout = (CardLayout) PanelCard.getLayout();
        layout.show(PanelCard, "user");
        panelUser1.LoadUser();
    }//GEN-LAST:event_menuUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCard;
    private usu.widget.glass.ButtonImageReflection btnExit;
    private com.stripbandunk.jglasspane.component.ImageTransitionComponent imageTransitionComponent1;
    private com.stripbandunk.jglasspane.JGlassPane jGlassPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelTgl;
    private javax.swing.JLabel lblJam;
    private usu.widget.glass.ButtonImageReflection menuAbsen;
    private usu.widget.glass.ButtonImageReflection menuGuru;
    private usu.widget.glass.ButtonImageReflection menuKelas;
    private usu.widget.glass.ButtonImageReflection menuLaporan;
    private usu.widget.glass.ButtonImageReflection menuMapel;
    private usu.widget.glass.ButtonImageReflection menuNilai;
    private usu.widget.glass.ButtonImageReflection menuSiswa;
    private usu.widget.glass.ButtonImageReflection menuUser;
    private MI_MAK.absen.PanelAbsen panelAbsen1;
    private MI_MAK.guru.PanelGuruTab panelGuruTab1;
    private MI_MAK.widget.PanelImageBackground panelImageBackground1;
    private MI_MAK.kelas.PanelKelas panelKelas1;
    private MI_MAK.laporanPanel.PanelLaporan panelLaporan1;
    private MI_MAK.mapel.PanelMapel panelMapel1;
    private javax.swing.JPanel panelMenu;
    private MI_MAK.nilai.PanelNilaiTab panelNilaiTab1;
    private MI_MAK.siswa.PanelSiswa panelSiswa1;
    private MI_MAK.user.PanelUser panelUser1;
    private MI_MAK.Welcome welcome1;
    // End of variables declaration//GEN-END:variables
}
