/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MI_MAK.guru;

/**
 *
 * @author Imam-pc
 */
public class PanelGuruTab extends javax.swing.JPanel {

    /**
     * Creates new form PanelGuruTab
     */
    public PanelGuruTab() {
        initComponents();
    }
    
    public void LoadGuru(){
        panelGuru1.LoadGuru();
        panelMengajar1.LoadMengajar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelGuru1 = new MI_MAK.guru.PanelGuru();
        panelMengajar1 = new MI_MAK.mengajar.PanelMengajar();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTabbedPane1.addTab("Data Guru", panelGuru1);
        jTabbedPane1.addTab("Jadwal Mengajar", panelMengajar1);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private MI_MAK.guru.PanelGuru panelGuru1;
    private MI_MAK.mengajar.PanelMengajar panelMengajar1;
    // End of variables declaration//GEN-END:variables
}
