/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MI_MAK.nilai;

/**
 *
 * @author Imam-pc
 */
public class PanelNilaiTab extends javax.swing.JPanel {

    /**
     * Creates new form PanelNilai
     */
    public PanelNilaiTab() {
        initComponents();
        
    }
    
    public void LoadComb(){
        
        panelPenilaian1.LoadKelasCombo();
        panelPenilaian1.LoadMapelCombo();
        panelNilaiRangking1.LoadKelasCombo();
        panelNilaiRekap1.LoadKelasCombo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelPenilaian1 = new MI_MAK.nilai.PanelPenilaian();
        panelNilaiRekap1 = new MI_MAK.nilai.PanelNilaiRekap();
        panelNilaiRangking1 = new MI_MAK.nilai.PanelNilaiRangking();

        setOpaque(false);

        jTabbedPane1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jTabbedPane1.addTab("Nilai Siswa", panelPenilaian1);
        jTabbedPane1.addTab("Nilai Rekap", panelNilaiRekap1);
        jTabbedPane1.addTab("Rangking", panelNilaiRangking1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private MI_MAK.nilai.PanelNilaiRangking panelNilaiRangking1;
    private MI_MAK.nilai.PanelNilaiRekap panelNilaiRekap1;
    private MI_MAK.nilai.PanelPenilaian panelPenilaian1;
    // End of variables declaration//GEN-END:variables
}
