/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MI_MAK.nilai;

import MI_MAK.dao.Kelas;
import MI_MAK.dao.PenilaianRekap;
import MI_MAK.dao.Siswa;
import MI_MAK.service.KelasService;
import MI_MAK.service.PenilaianService;
import MI_MAK.service.SiswaService;
import com.stripbandunk.jwidget.model.DynamicTableModel;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingWorker;

/**
 *
 * @author Imam-pc
 */
public final class PanelNilaiRekap extends javax.swing.JPanel {
    
     private final int thnFrom;
    private final int thnTo;

    private final DynamicTableModel<PenilaianRekap> tableModelRekap;
    public PanelNilaiRekap() {
        initComponents();
        
        tableModelRekap = new DynamicTableModel<>(PenilaianRekap.class);
        tabelNilaiRekap.setDynamicModel(tableModelRekap);
        
        Date date = new Date();
        Calendar now = Calendar.getInstance();
        now.setTimeInMillis(date.getTime());
        
        thnFrom = date.getYear()+ 1900;
        thnTo = date.getYear()+ 1900;
        
        ChooseThnAjaranFromRekap.setValue(thnFrom - 1);
        ChooseThnAjaranToRekap.setValue(thnTo);
        
        LoadPenilaianRekapAll(String.valueOf(ChooseThnAjaranFromRekap.getValue())+"/"+String.valueOf(ChooseThnAjaranToRekap.getValue()));
        
    }
    private final PenilaianService service = new PenilaianService();
    public void LoadPenilaianRekapAll(String kd){
        
        new SwingWorker<List<PenilaianRekap>, Object>(){

            @Override
            protected List<PenilaianRekap> doInBackground() throws Exception {
                
                Thread.sleep(1000);
                List<PenilaianRekap> list = service.getNilaiRekapAll(kd);

                return list;
            }

            @Override
            protected void done() {
                try {
                    tableModelRekap.clear();
                    for(PenilaianRekap jsb : get()){
                    tableModelRekap.add(jsb);
                }
                } catch (InterruptedException | ExecutionException ex) {
                    Logger.getLogger(PanelNilai_old.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
  
        }.execute();
        
    }
    
    public void LoadPenilaianRekapParam(String sws, String kls, String thn, String smtr ){
        
        new SwingWorker<List<PenilaianRekap>, Object>(){

            @Override
            protected List<PenilaianRekap> doInBackground() throws Exception {
                
                Thread.sleep(1000);
                List<PenilaianRekap> list = service.getNilaiRekapParam(sws, kls, thn, smtr);

                return list;
            }

            @Override
            protected void done() {
                try {
                    tableModelRekap.clear();
                    for(PenilaianRekap jsb : get()){
                    tableModelRekap.add(jsb);
                }
                } catch (InterruptedException | ExecutionException ex) {
                    Logger.getLogger(PanelNilai_old.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
  
        }.execute();
        
    }
    
    public void LoadKelasCombo(){
        KelasService ks = new KelasService();
        List<Kelas> list =  ks.selectKelas();
        
        list.stream().forEach((kelas) -> {
            comboKlsRekap.addItem(kelas);
            System.out.println("load Kelas: "+kelas);
        });
    }
    
    public void LoadSiswaByKelasCombo(String id){
        SiswaService vs = new SiswaService();
        List<Siswa> list =  vs.getSiswaByKelas(id);
        comboSiswaRekap.removeAllItems();
        comboSiswaRekap.addItem("All");
        list.stream().forEach((sw) -> {
            comboSiswaRekap.addItem(sw);
            System.out.println("load Siswa: "+sw);
        });
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelKdKls = new javax.swing.JLabel();
        labelNmKls = new javax.swing.JLabel();
        labelKdSiswa = new javax.swing.JLabel();
        labelNmSiswa = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        comboKlsRekap = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        comboSmstrRekap = new javax.swing.JComboBox();
        btnCariRekap = new javax.swing.JButton();
        btnTmplknSmua1 = new javax.swing.JButton();
        ChooseThnAjaranFromRekap = new com.toedter.calendar.JYearChooser();
        jLabel19 = new javax.swing.JLabel();
        ChooseThnAjaranToRekap = new com.toedter.calendar.JYearChooser();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        comboSiswaRekap = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelNilaiRekap = new com.stripbandunk.jwidget.JDynamicTable();

        labelKdKls.setText("jLabel1");

        labelNmKls.setText("jLabel2");

        labelKdSiswa.setText("jLabel1");

        labelNmSiswa.setText("jLabel1");

        setOpaque(false);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Filter By", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N
        jPanel4.setOpaque(false);

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel12.setText("Kelas");

        comboKlsRekap.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        comboKlsRekap.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All" }));
        comboKlsRekap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboKlsRekapActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel14.setText(":");

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel15.setText("Tahun Ajaran ");

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel16.setText("Semester");

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel17.setText(":");

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel18.setText(":");

        comboSmstrRekap.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        comboSmstrRekap.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Ganjil", "Genap" }));

        btnCariRekap.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnCariRekap.setText("Cari");
        btnCariRekap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariRekapActionPerformed(evt);
            }
        });

        btnTmplknSmua1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnTmplknSmua1.setText("Tampilkan Semua");
        btnTmplknSmua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTmplknSmua1ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel19.setText("/");

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel13.setText("Siswa");

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel20.setText(":");

        comboSiswaRekap.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        comboSiswaRekap.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All" }));
        comboSiswaRekap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSiswaRekapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(ChooseThnAjaranFromRekap, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChooseThnAjaranToRekap, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboKlsRekap, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboSmstrRekap, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboSiswaRekap, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(64, 64, 64)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCariRekap, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTmplknSmua1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 72, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnCariRekap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTmplknSmua1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(jLabel18))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(jLabel17)
                                .addComponent(comboSmstrRekap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ChooseThnAjaranFromRekap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(ChooseThnAjaranToRekap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(comboKlsRekap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel20)
                            .addComponent(comboSiswaRekap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setOpaque(false);

        jScrollPane2.setViewportView(tabelNilaiRekap);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboKlsRekapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboKlsRekapActionPerformed
        // TODO add your handling code here:

        if(comboKlsRekap.getSelectedItem().equals("All")){

            LoadSiswaByKelasCombo("");
            System.out.println("combo kelas index 1 : "+comboKlsRekap.getSelectedIndex());
            System.out.println("combo kelas item 1 : "+comboKlsRekap.getSelectedItem());
            // JFrame frame = new JFrame("Warning");
            // JOptionPane.showMessageDialog(frame, "All Kelas");
        }else if(comboKlsRekap.getSelectedIndex()== -1){
            System.out.println("combo kelas index 2: "+comboKlsRekap.getSelectedIndex());
            System.out.println("combo kelas item 2: "+comboKlsRekap.getSelectedItem());
            // JFrame frame = new JFrame("Warning");
            // JOptionPane.showMessageDialog(frame, "All Kelas");
        }else{

            String lblKodeKls;
            lblKodeKls = comboKlsRekap.getSelectedItem().toString();
            System.out.println("combo kelas: "+lblKodeKls);
            String[] prt = lblKodeKls.split("-");
            String varStrKode = prt[0];
            String varStrNama = prt[1];
            System.out.println("split kode: "+varStrKode);
            System.out.println("split nama: "+varStrNama);
            labelKdKls.setText(varStrKode);
            labelNmKls.setText(varStrNama);

            LoadSiswaByKelasCombo(labelKdKls.getText());

        }

    }//GEN-LAST:event_comboKlsRekapActionPerformed

    private void btnCariRekapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariRekapActionPerformed
        // TODO add your handling code here:
        String varSiswa;
        String varKls;
        String varSmstr;
        String varThn;

        String thF;
        String thT;

        if(comboSiswaRekap.getSelectedItem().equals("All")){
            varSiswa = "";
        }else{
            varSiswa = labelKdSiswa.getText();
        }

        if(comboKlsRekap.getSelectedItem().equals("All")){
            varKls = "";
        }else{
            varKls = labelKdKls.getText();
        }

        if(comboSmstrRekap.getSelectedItem().equals("All")){
            varSmstr = "";
        }else{
            varSmstr = comboSmstrRekap.getSelectedItem().toString();
        }

        if(ChooseThnAjaranFromRekap.getValue() <= 0 || ChooseThnAjaranToRekap.getValue() <= 0){
            thF = "";
            thT = "";
            varThn = thF+"/"+thT;
        }else{
            thF = String.valueOf(ChooseThnAjaranFromRekap.getValue());
            thT = String.valueOf(ChooseThnAjaranToRekap.getValue());
            varThn = thF+"/"+thT;
        }

        LoadPenilaianRekapParam(varSiswa, varKls, varThn, varSmstr);

    }//GEN-LAST:event_btnCariRekapActionPerformed

    private void btnTmplknSmua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTmplknSmua1ActionPerformed
        // TODO add your handling code here:
        LoadPenilaianRekapAll(String.valueOf(ChooseThnAjaranFromRekap.getValue())+"/"+String.valueOf(ChooseThnAjaranToRekap.getValue()));
        comboKlsRekap.setSelectedItem("All");
        comboSiswaRekap.setSelectedItem("All");
        comboSmstrRekap.setSelectedItem("All");

    }//GEN-LAST:event_btnTmplknSmua1ActionPerformed

    private void comboSiswaRekapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSiswaRekapActionPerformed
        // TODO add your handling code here:

        if(comboSiswaRekap.getSelectedIndex() == -1 ){
            System.out.println("combo siswa index 1 : "+comboSiswaRekap.getSelectedIndex());
            System.out.println("combo siswa item 1 : "+comboSiswaRekap.getSelectedItem());
        }else if(comboSiswaRekap.getSelectedItem().equals("All")){
            //  LoadPenilaianRekapAll(thnFrom-1+"/"+thnTo);
            System.out.println("combo siswa index 1 : "+comboSiswaRekap.getSelectedIndex());
            System.out.println("combo siswa item 1 : "+comboSiswaRekap.getSelectedItem());
        }else{

            String lblKodeSws;
            lblKodeSws = comboSiswaRekap.getSelectedItem().toString();
            System.out.println("combo Siswa: "+lblKodeSws);
            String[] prt = lblKodeSws.split("-");
            String varStrKode = prt[0];
            String varStrNama = prt[1];
            System.out.println("split kode: "+varStrKode);
            System.out.println("split nama: "+varStrNama);
            labelKdSiswa.setText(varStrKode);
            labelNmSiswa.setText(varStrNama);

            // LoadPenilaianRekap(labelKdSiswa.getText());

        }

    }//GEN-LAST:event_comboSiswaRekapActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JYearChooser ChooseThnAjaranFromRekap;
    private com.toedter.calendar.JYearChooser ChooseThnAjaranToRekap;
    private javax.swing.JButton btnCariRekap;
    private javax.swing.JButton btnTmplknSmua1;
    private javax.swing.JComboBox comboKlsRekap;
    private javax.swing.JComboBox comboSiswaRekap;
    private javax.swing.JComboBox comboSmstrRekap;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelKdKls;
    private javax.swing.JLabel labelKdSiswa;
    private javax.swing.JLabel labelNmKls;
    private javax.swing.JLabel labelNmSiswa;
    private com.stripbandunk.jwidget.JDynamicTable tabelNilaiRekap;
    // End of variables declaration//GEN-END:variables
}
