/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MI_MAK.absen;

import MI_MAK.dao.Absen;
import MI_MAK.dao.Kelas;
import MI_MAK.dao.Siswa;
import MI_MAK.dao.ViewSiswa;
import MI_MAK.service.AbsenService;
import MI_MAK.service.KelasService;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Imam-pc
 */
public class UbahAbsen extends javax.swing.JDialog {

    private Siswa siswa;
    private String kdKelas;
    private String nmKls;
    private Absen absen;
    public UbahAbsen() {
        setModal(true);
        initComponents();
        
        setGlassPane(jGlassPane1);
        getGlassPane().setVisible(true);
        
        jGlassPane1.addGlassPaneComponent(messageComponent1);
        
    }
    
    public Absen ubahAbsen(Absen param){
        
        LoadKelasCombo();
        
        txtKodeAbsen.setText(param.getKd_absen());
        txtKodeSiswa.setText(param.getKd_siswa());
        txtNamaSiswa.setText(param.getNama_siswa());
        comboKelas.setSelectedItem(param.getKd_kelas()+"-"+param.getNama_kelas());
        dateAbsenDari.setDate(param.getTglDari());
        dateAbsenSampai.setDate(param.getTglSampai());
        txtKet.setText(param.getKet());
        
        if(param.getSemester().equals("Ganjil")){
            rbGanjil.setSelected(true);
            rbGenap.setSelected(false);
        }else{
            rbGenap.setSelected(true);
            rbGanjil.setSelected(false);
        }
        if(param.getAlpa() > 0){
            comboStatus.setSelectedItem("Alpa");
            txtJmlh.setValue(param.getAlpa());
            labelJmlh.setText("Jumlah Alpa");
        }else if(param.getIzin() > 0){
            comboStatus.setSelectedItem("Izin");
            txtJmlh.setValue(param.getIzin());
            labelJmlh.setText("Jumlah Izin");
        }else{
            comboStatus.setSelectedItem("Sakit");
            txtJmlh.setValue(param.getSakit());
            labelJmlh.setText("Jumlah Sakit");
        }
        
        
        
        labelID.setText(String.valueOf(param.getId()));
        
        absen = param;
        setLocationRelativeTo(this);
        setVisible(true);
        
        return absen;
    }
    
    public void LoadKelasCombo(){
        KelasService ss = new KelasService();
        List<Kelas> list =  ss.selectKelas();
        comboKelas.removeAllItems();
        comboKelas.addItem("Pilih");
        list.stream().forEach((kelas) -> {
            comboKelas.addItem(kelas);
        });
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jGlassPane1 = new com.stripbandunk.jglasspane.JGlassPane();
        messageComponent1 = new com.stripbandunk.jglasspane.component.MessageComponent();
        labelKodeKelas = new javax.swing.JLabel();
        labelNIP = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        lblKodeKelas = new javax.swing.JLabel();
        labelNmKelas = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();
        panelImageBackground1 = new MI_MAK.widget.PanelImageBackground();
        jLabel1 = new javax.swing.JLabel();
        txtKodeAbsen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dateAbsenDari = new com.toedter.calendar.JDateChooser();
        comboKelas = new javax.swing.JComboBox();
        rbGanjil = new javax.swing.JRadioButton();
        rbGenap = new javax.swing.JRadioButton();
        comboStatus = new javax.swing.JComboBox();
        txtKodeSiswa = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNamaSiswa = new javax.swing.JTextField();
        labelJmlh = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtJmlh = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        dateAbsenSampai = new com.toedter.calendar.JDateChooser();
        txtKet = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        labelNmKelas.setText("jLabel15");

        labelID.setText("jLabel15");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        panelImageBackground1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ubah Absensi Siswa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("Kode Absen");

        txtKodeAbsen.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtKodeAbsen.setEnabled(false);
        txtKodeAbsen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKodeAbsenKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setText("Tanggal Dari");

        jPanel1.setOpaque(false);

        btnSimpan.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimpan);

        btnBatal.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel1.add(btnBatal);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setText("Kelas");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setText(":");

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel7.setText(":");

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel8.setText(":");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setText("Kode Siswa");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setText("Semester");

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setText("Ketidakhadiran");

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel10.setText(":");

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel11.setText(":");

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel12.setText(":");

        dateAbsenDari.setDate(new java.util.Date());
        dateAbsenDari.setDateFormatString("dd-MMM-yyyy");
        dateAbsenDari.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        dateAbsenDari.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateAbsenDariPropertyChange(evt);
            }
        });

        comboKelas.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        comboKelas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih" }));
        comboKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboKelasActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbGanjil);
        rbGanjil.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        rbGanjil.setSelected(true);
        rbGanjil.setText("Ganjil");
        rbGanjil.setOpaque(false);

        buttonGroup1.add(rbGenap);
        rbGenap.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        rbGenap.setText("Genap");
        rbGenap.setOpaque(false);

        comboStatus.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        comboStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih", "Sakit", "Izin", "Alpa" }));
        comboStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboStatusActionPerformed(evt);
            }
        });

        txtKodeSiswa.setEditable(false);
        txtKodeSiswa.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtKodeSiswa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKodeSiswaKeyTyped(evt);
            }
        });

        btnCari.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel13.setText("Nama Siswa");

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel14.setText(":");

        txtNamaSiswa.setEditable(false);
        txtNamaSiswa.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtNamaSiswa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaSiswaKeyTyped(evt);
            }
        });

        labelJmlh.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labelJmlh.setText("Jumlah");

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel16.setText(":");

        txtJmlh.setEditable(false);
        txtJmlh.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtJmlh.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        txtJmlh.setValue(new java.lang.Long(0));

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel15.setText("Tanggal Sampai");

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel17.setText(":");

        dateAbsenSampai.setDate(new java.util.Date());
        dateAbsenSampai.setDateFormatString("dd-MMM-yyyy");
        dateAbsenSampai.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        dateAbsenSampai.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateAbsenSampaiPropertyChange(evt);
            }
        });

        txtKet.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel21.setText(":");

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel20.setText("Keterangan");

        javax.swing.GroupLayout panelImageBackground1Layout = new javax.swing.GroupLayout(panelImageBackground1);
        panelImageBackground1.setLayout(panelImageBackground1Layout);
        panelImageBackground1Layout.setHorizontalGroup(
            panelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImageBackground1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelImageBackground1Layout.createSequentialGroup()
                        .addGroup(panelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panelImageBackground1Layout.createSequentialGroup()
                                    .addGroup(panelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                                    .addGap(6, 6, 6)
                                    .addGroup(panelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(panelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtKodeAbsen)
                                        .addComponent(dateAbsenDari, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)))
                                .addGroup(panelImageBackground1Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dateAbsenSampai, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)))
                            .addGroup(panelImageBackground1Layout.createSequentialGroup()
                                .addGroup(panelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(labelJmlh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(panelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelImageBackground1Layout.createSequentialGroup()
                                        .addComponent(rbGanjil)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbGenap))
                                    .addComponent(comboKelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(panelImageBackground1Layout.createSequentialGroup()
                                        .addComponent(txtKodeSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnCari))
                                    .addComponent(txtNamaSiswa)
                                    .addComponent(txtJmlh, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelImageBackground1Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtKet)))
                        .addGap(0, 101, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelImageBackground1Layout.setVerticalGroup(
            panelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImageBackground1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKodeAbsen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel7))
                    .addComponent(dateAbsenDari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel17))
                    .addComponent(dateAbsenSampai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(comboKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(txtKodeSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(txtNamaSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(rbGanjil)
                    .addComponent(rbGenap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJmlh)
                    .addComponent(jLabel16)
                    .addComponent(txtJmlh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelImageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(txtKet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(panelImageBackground1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        
        int closing;
            closing = JOptionPane.showConfirmDialog(this,
        "Apakah anda yakin, ingin batal?", "Konfirmasi",JOptionPane.YES_NO_OPTION);
        if (closing==0){
            dispose();
            
        }else{
            this.show();
        }
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        
         Long dtMin = (Long) txtJmlh.getValue();
        
        if(txtKodeAbsen.getText().trim().isEmpty()){
            messageComponent1.showWarning("Kode Absen Kosong");
        }else if(comboKelas.getSelectedItem().equals("Pilih")){
            messageComponent1.showWarning("Kelas Kosong");
        }else if(txtKodeSiswa.getText().trim().isEmpty()){
            messageComponent1.showWarning("Siswa Kosong");
        }else if(comboStatus.getSelectedItem().equals("Pilih")){
            messageComponent1.showWarning("Ketidakhadiran Kosong");
        }else if(txtJmlh.getValue() == null || dtMin <= 0){
            messageComponent1.showWarning("Jumlah Kosong");
        }else{
            
            absen = new Absen();
            absen.setKd_absen(txtKodeAbsen.getText());
            absen.setKd_kelas(labelKodeKelas.getText());
            absen.setKd_siswa(txtKodeSiswa.getText());
            absen.setNama_kelas(labelNmKelas.getText());
            absen.setNama_siswa(txtNamaSiswa.getText());
            absen.setId(Integer.parseInt(labelID.getText()));
            
            if(rbGanjil.isSelected()==true){
                absen.setSemester("Ganjil");
            }else{
                absen.setSemester("Genap");
            }
            
            if(comboStatus.getSelectedItem().equals("Sakit")){
                absen.setSakit((Long) txtJmlh.getValue());
                absen.setIzin(Long.valueOf(0));
                absen.setAlpa(Long.valueOf(0));
            }else if(comboStatus.getSelectedItem().equals("Izin")){
                absen.setIzin((Long) txtJmlh.getValue());
                absen.setAlpa(Long.valueOf(0));
                absen.setSakit(Long.valueOf(0));
            }else{
                absen.setAlpa((Long) txtJmlh.getValue());
                absen.setIzin(Long.valueOf(0));
                absen.setSakit(Long.valueOf(0));
            }
            absen.setTglDari(new java.sql.Date(dateAbsenDari.getDate().getTime()));
            absen.setTglSampai(new java.sql.Date(dateAbsenSampai.getDate().getTime()));
            absen.setTgl_ubah(new java.sql.Timestamp(new java.util.Date().getTime()));
            
            AbsenService service = new AbsenService();
            service.update(absen);
            dispose();
        }
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtKodeAbsenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodeAbsenKeyTyped
        // TODO add your handling code here:
        
        char c=evt.getKeyChar();

        if(Character.isLetter(c) || Character.isISOControl(c) || Character.isDigit(c))
        {
            evt = evt;
        }else{
            evt.consume();
        }
        
    }//GEN-LAST:event_txtKodeAbsenKeyTyped

    private void comboKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboKelasActionPerformed
        // TODO add your handling code here:
        switch (comboKelas.getSelectedIndex()) {
            case -1:
                kdKelas = "";
                txtKodeSiswa.setText("");
                txtNamaSiswa.setText("");
                break;
            case 0:
                kdKelas = "";
                txtKodeSiswa.setText("");
                txtNamaSiswa.setText("");
                break;
            default:
                txtKodeSiswa.setText("");
                txtNamaSiswa.setText("");
                String kodeKls;
                kodeKls = comboKelas.getSelectedItem().toString();
                System.out.println("combo mapel: "+kodeKls);
                String[] prt = kodeKls.split("-");
                String varStrKode = prt[0];
                labelNmKelas.setText(prt[1]);
                System.out.println("split kode: "+varStrKode);
                System.out.println("split nama: "+labelNmKelas.getText());
                lblKodeKelas.setText(varStrKode);
                break;
        }
        
        
    }//GEN-LAST:event_comboKelasActionPerformed

    private void txtKodeSiswaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodeSiswaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeSiswaKeyTyped

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        if(comboKelas.getSelectedItem().equals("Pilih")){
            messageComponent1.showWarning("Kelas belum dipilih");
        }else{
            
            CariSiswa cariSiswa = new CariSiswa();
            ViewSiswa sw = cariSiswa.viewCariSiswa(lblKodeKelas.getText());
            if(sw != null){
                
                txtKodeSiswa.setText(sw.getKd_siswa());
                txtNamaSiswa.setText(sw.getNm_siswa());
                lblKodeKelas.setText(sw.getKd_kelas());
                labelNmKelas.setText(sw.getNm_kelas());
                
            }else{
                txtKodeSiswa.setText("");
                txtNamaSiswa.setText("");
                lblKodeKelas.setText("");
                labelNmKelas.setText("");
                
            }
            
        }
        
        
    }//GEN-LAST:event_btnCariActionPerformed

    private void txtNamaSiswaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaSiswaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaSiswaKeyTyped

    private void comboStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboStatusActionPerformed
        // TODO add your handling code here:
        
        if(comboStatus.getSelectedItem().equals("Pilih")){
            labelJmlh.setText("Jumlah");
        }else if(comboStatus.getSelectedItem().equals("Sakit")){
            labelJmlh.setText("Jumlah Sakit");
        }else if(comboStatus.getSelectedItem().equals("Izin")){
            labelJmlh.setText("Jumlah Izin");
        }else{
            labelJmlh.setText("Jumlah Alpa");
        }
        
        
    }//GEN-LAST:event_comboStatusActionPerformed

    private void dateAbsenSampaiPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateAbsenSampaiPropertyChange
        // TODO add your handling code here:
        
        Date dayFrom = dateAbsenDari.getDate();
        Date dayTo = dateAbsenSampai.getDate();
        long dif = dayTo.getTime() - dayFrom.getTime();
        long daysBetween = ((dif / (1000*60*60*24))+1);
        System.out.println("jmlh days: "+daysBetween);
        txtJmlh.setValue(daysBetween);
        
    }//GEN-LAST:event_dateAbsenSampaiPropertyChange

    private void dateAbsenDariPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateAbsenDariPropertyChange
        // TODO add your handling code here:
         Date dayFrom = dateAbsenDari.getDate();
        Date dayTo = dateAbsenSampai.getDate();
        long dif = dayTo.getTime() - dayFrom.getTime() ;
        long daysBetween = ((dif / (1000*60*60*24))+1);
        System.out.println("jmlh days: "+daysBetween);
        txtJmlh.setValue(daysBetween);
    }//GEN-LAST:event_dateAbsenDariPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnSimpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox comboKelas;
    private javax.swing.JComboBox comboStatus;
    private com.toedter.calendar.JDateChooser dateAbsenDari;
    private com.toedter.calendar.JDateChooser dateAbsenSampai;
    private com.stripbandunk.jglasspane.JGlassPane jGlassPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelJmlh;
    private javax.swing.JLabel labelKodeKelas;
    private javax.swing.JLabel labelNIP;
    private javax.swing.JLabel labelNmKelas;
    private javax.swing.JLabel lblKodeKelas;
    private com.stripbandunk.jglasspane.component.MessageComponent messageComponent1;
    private MI_MAK.widget.PanelImageBackground panelImageBackground1;
    private javax.swing.JRadioButton rbGanjil;
    private javax.swing.JRadioButton rbGenap;
    private javax.swing.JFormattedTextField txtJmlh;
    private javax.swing.JTextField txtKet;
    private javax.swing.JTextField txtKodeAbsen;
    private javax.swing.JTextField txtKodeSiswa;
    private javax.swing.JTextField txtNamaSiswa;
    // End of variables declaration//GEN-END:variables
}
